const pgn = '[Event "?"]\n'
    + '[Site "?"]\n'
    + '[Date "????.??.??"]\n'
    + '[Round "?"]\n'
    + '[White "?"]\n'
    + '[Black "?"]\n'
    + '[Result "*"]\n'
    + '\n'
    + '1. e4 e5 \n'
    + '    (1. ... d5 2. exd5)\n'
    + '    (1. ... c5 2. d4)\n'
    + '    (1. ... Nc6 2. Nc3)\n'
    + '2. Nf3 *'
    + '\n';

const pgn1 = '[Event "ICC 5 0 u"]\n'
    + '[Site "Internet Chess Club"]\n'
    + '[Date "2019.10.13"]\n'
    + '[Round "-"]\n'
    + '[White "uiuxtest1"]\n'
    + '[Black "uiuxtest2"]\n'
    + '[Result "*"]\n'
    + '[ICCResult "Game adjourned when White disconnected"]\n'
    + '[WhiteElo "1400"]\n'
    + '[BlackElo "1400"]\n'
    + '[Opening "Two knights defense"]\n'
    + '[ECO "C55"]\n'
    + '[NIC "IG.01"]\n'
    + '[Time "13:08:42"]\n'
    + '[TimeControl "300+0"]\n'
    + '\n'
    + '1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. c3 d5 5. exd5 Nxd5 6. Qb3 Be6 7. O-O Be7\n'
    + '8. d3 O-O 9. Re1 {Game adjourned when White disconnected} *\n'
    + '\n'
    + '[Event "ICC 5 0 u"]\n'
    + '[Site "Internet Chess Club"]\n'
    + '[Date "2019.10.13"]\n'
    + '[Round "-"]\n'
    + '[White "uiuxtest1"]\n'
    + '[Black "uiuxtest2"]\n'
    + '[Result "*"]\n'
    + '[ICCResult "Game adjourned when White disconnected"]\n'
    + '[WhiteElo "1400"]\n'
    + '[BlackElo "1400"]\n'
    + '[Opening "Two knights defense"]\n'
    + '[ECO "C55"]\n'
    + '[NIC "IG.01"]\n'
    + '[Time "13:08:42"]\n'
    + '[TimeControl "300+0"]\n'
    + '\n'
    + '1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. c3 d5 5. exd5 Nxd5 6. Qb3 Be6 7. O-O Be7\n'
    + '8. d3 O-O 9. Re1 {Game adjourned when White disconnected} *';

const pgn2 = '[Event "Waldshut Sen\\Nes"]\n'
    + '[Site "Waldshut Sen\\Nes"]\n'
    + '[Date "1991.??.??"]\n'
    + '[Round "1"]\n'
    + '[White "Nadenau, Oskar"]\n'
    + '[Black "Seiter, G"]\n'
    + '[Result "1-0"]\n'
    + '[ECO "A30d"]\n'
    + '[EventDate "1991.??.??"]\n'
    + '\n'
    + '1. c4 c5 2. Nf3 Nf6 3. g3 g6 4. Bg2 Bg7 5. O-O d6 6. d4 cxd4 7. Nxd4 O-O \n'
    + '8. Nc3 Qc7 9. b3 Bd7 10. Bb2 Nc6 11. Nc2 a6 12. e4 Rad8 13. Ne3 e6 14. Qd2\n'
    + 'Ne7 15. Rac1 Bc6 16. Rfd1 Rd7 17. Qc2 Rc8 18. Qe2 Qd8 19. h3 d5 20. cxd5 \n'
    + 'exd5 21. Ncxd5 Nfxd5 22. exd5 Bb5 23. Rxc8 Qxc8 24. Qd2 Bxb2 25. Qxb2 Rd6 \n'
    + '26. Ng4 Nf5 27. Nf6+ Kf8 28. Nxh7+ Kg8 29. Nf6+ Kf8 30. Ne4 Rd8 31. Qh8+ \n'
    + 'Ke7 32. Qf6+ Kd7 33. Qxf7+ 1-0';

const pgn3 = '[Event "Waldshut Sen\\Nes"]\n'
    + '[Site "Waldshut Sen\\Nes"]\n'
    + '[Date "1991.??.??"]\n'
    + '[Round "1"]\n'
    + '[White "Nadenau, Oskar"]\n'
    + '[Black "Seiter, G"]\n'
    + '[Result "1-0"]\n'
    + '[ECO "A30d"]\n'
    + '[EventDate "1991.??.??"]\n'
    + '\n'
    + '[Event "Waldshut Sen\\Nes"]\n'
    + '[Site "Waldshut Sen\\Nes"]\n'
    + '[Date "1991.??.??"]\n'
    + '[Round "1"]\n'
    + '[White "Nadenau, Oskar"]\n'
    + '[Black "Seiter, G"]\n'
    + '[Result "1-0"]\n'
    + '[ECO "A30d"]\n'
    + '[EventDate "1991.??.??"]\n'
    + '\n'
    + '[Event "Waldshut Sen\\Nes"]\n'
    + '[Site "Waldshut Sen\\Nes"]\n'
    + '[Date "1991.??.??"]\n'
    + '[Round "1"]\n'
    + '[White "Nadenau, Oskar"]\n'
    + '[Black "Seiter, G"]\n'
    + '[Result "1-0"]\n'
    + '[ECO "A30d"]\n'
    + '[EventDate "1991.??.??"]\n'
    + '\n';

const pgn4 = '[Event "Waldshut Sen\\Nes"]\n'
    + '[Site "Waldshut Sen\\Nes"]\n'
    + '[Date "1991.??.??"]\n'
    + '[Round "1"]\n'
    + '[White "Nadenau, Oskar"]\n'
    + '[Black "Seiter, G"]\n'
    + '[Result "1-0"]\n'
    + '[ECO "A30d"]\n'
    + '[EventDate "1991.??.??"]\n'
    + '\n*\n'
    + '[Event "Waldshut Sen\\Nes"]\n'
    + '[Site "Waldshut Sen\\Nes"]\n'
    + '[Date "1991.??.??"]\n'
    + '[Round "1"]\n'
    + '[White "Nadenau, Oskar"]\n'
    + '[Black "Seiter, G"]\n'
    + '[Result "1-0"]\n'
    + '[ECO "A30d"]\n'
    + '[EventDate "1991.??.??"]\n'
    + '\n*\n'
    + '[Event "Waldshut Sen\\Nes"]\n'
    + '[Site "Waldshut Sen\\Nes"]\n'
    + '[Date "1991.??.??"]\n'
    + '[Round "1"]\n'
    + '[White "Nadenau, Oskar"]\n'
    + '[Black "Seiter, G"]\n'
    + '[Result "1-0"]\n'
    + '[ECO "A30d"]\n'
    + '[EventDate "1991.??.??"]\n'
    + '\n*';
module.exports = [pgn, pgn1, pgn2, pgn3, pgn4];
